server.port=8082
spring.application.name=Notification Service
application.version=1.0.0
application.github=https://github.com/esap-mis

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate

spring.jackson.deserialization.fail-on-unknown-properties=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.threads.virtual.enabled=true

#debug
#debug=true
spring.jpa.show-sql=false
spring.jpa.format-sql=false
#logging.level.org.hibernate=DEBUG
logging.level.root=INFO
logging.level.com.baeldung=INFO
#logging.level.org.springframework.boot.autoconfigure=DEBUG
#logging.level.org.springframework.web=DEBUG

spring.kafka.admin.auto-create=false
spring.kafka.admin.fail-fast=false
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
notification.kafka.topic.welcome-email=${MAIL_TOPIC_NAME:user.registered.welcome-email}
notification.kafka.topic.push-notification=${NOTIFICATIONS_TOPIC_NAME:user.notification.push.requested}
notification.kafka.topic.token-registration=${NOTIFICATIONS_TOKENS_TOPIC_NAME:user.device.token.registered}

#spring.mail.protocol=smtp
#spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2