server.port=8000
spring.application.name=ESAP API Gateway
application.version=2.0.0

esap.jwt.secret=${JWT_SECRET:secret}
esap.jwt.issuer=${JWT_ISSUER:ru.javavlsu.kb.esap}

esap.routes.auth=${AUTH_SERVICE_URL:http://localhost:8081}
esap.routes.clinic=${CLINIC_SERVICE_URL:http://localhost:8082}
esap.routes.schedule=${SCHEDULE_SERVICE_URL:http://localhost:8083}
esap.routes.core=${CORE_SERVICE_URL:http://localhost:8080}

spring.cloud.gateway.x-forwarded.enabled=true
spring.cloud.gateway.default-filters:
  - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Allow-Headers, RETAIN_UNIQUE

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.health.probes.enabled=true
