# k8s/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: esap-config
  namespace: default
data:
  app_name: "esap"
  log_level: "INFO"
  # esap db
  esap_db: "esap"
  esap_db_url: "jdbc:postgresql://esap-db-service:5432/esap"
  # notifications db
  notifications_db: "notifications"
  notifications_db_host: "notifications-db-service"
  notifications_db_port: "27017"
  # kafka
  kafka_bootstrap_servers: "kafka-0.kafka-headless.default.svc.cluster.local:9092"
  mail_topic_name: "user.registered.welcome-email"
  notifications_topic_name: "user.notification.push.requested"
  notifications_tokens_topic_name: "user.device.token.registered"
  api_key: "fake-api-key-for-testing"
  mail_host: "smtp.gmail.com"
  mail_port: "587"
  mail_username: "esap.mis.clinic@gmail.com"
  api_url: "http://esap-service:8080" # Внутреннее DNS-имя