# k8s/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: esap-secret
  namespace: default
type: Opaque
data:
  esap_db_user: ZXNhcA==      # base64
  esap_db_password: ZXNhcA==
  mail_password: bndvbSBiamVkIG1pc2wgcnJkZg==
  notifications_db_user: dXNlcg==
  notifications_db_password: cGFzc3dvcmQ=