# k8s/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: esap-secret
  namespace: default
type: Opaque
data:
  db_user: ZXNhcA==      # base64
  db_password: ZXNhcA==  # base64
  mail_password: bndvbSBiamVkIG1pc2wgcnJkZg== # base64