# k8s/postgres/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esap-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esap-db
  template:
    metadata:
      labels:
        app: esap-db
    spec:
      containers:
        - name: esap-db
          image: postgres:17-alpine
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: esap-config
                  key: esap_db
            #Secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: esap-secret
                  key: esap_db_password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: esap-secret
                  key: esap_db_user
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: esap-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: esap-db-storage
          persistentVolumeClaim:
            claimName: esap-db-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esap-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---