# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esap-app
  namespace: default
  labels:
    app: esap
spec:
  replicas: 2  # Две реплики для отказоустойчивости
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: esap
  template:
    metadata:
      labels:
        app: esap
    spec:
      containers:
        - name: esap-app
          image: docker.io/library/esap-mis-core:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: esap-config
                  key: esap_db_url
            #Secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: esap-secret
                  key: esap_db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: esap-secret
                  key: esap_db_password

            # Kafka
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: esap-config
                  key: kafka_bootstrap_servers
            - name: MAIL_TOPIC_NAME
              valueFrom:
                configMapKeyRef:
                  name: esap-config
                  key: mail_topic_name
            - name: NOTIFICATIONS_TOPIC_NAME
              valueFrom:
                configMapKeyRef:
                  name: esap-config
                  key: notifications_topic_name
            - name: NOTIFICATIONS_TOKENS_TOPIC_NAME
              valueFrom:
                configMapKeyRef:
                  name: esap-config
                  key: notifications_tokens_topic_name
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 5
            failureThreshold: 3
      restartPolicy: Always