apiVersion: apps/v1
kind: Deployment
metadata:
  name: esap-core
  namespace: default
  labels:
    app: esap-core
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: esap-core
  template:
    metadata:
      labels:
        app: esap-core
    spec:
      containers:
        - name: esap-core
          image: docker.io/library/esap-mis-core:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: esap-config
                  key: esap_core_db_url
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: esap-secret
                  key: esap_db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: esap-secret
                  key: esap_db_password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: esap-secret
                  key: jwt_secret
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: esap-config
                  key: kafka_bootstrap_servers
            - name: NOTIFICATIONS_TOKENS_TOPIC_NAME
              valueFrom:
                configMapKeyRef:
                  name: esap-config
                  key: notifications_tokens_topic_name
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: esap-config
                  key: auth_service_url
            - name: CLINIC_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: esap-config
                  key: clinic_service_url
            - name: SCHEDULE_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: esap-config
                  key: schedule_service_url
            - name: API_KEY
              valueFrom:
                configMapKeyRef:
                  name: esap-config
                  key: api_key
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 5
            failureThreshold: 3
      restartPolicy: Always
