apiVersion: v1
kind: Service
metadata:
  name: esap-core
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: esap-core
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
